spring.application.name=DataPulse API

# Active Profile (Change to 'mysql' when you want to switch)
spring.profiles.active=mysql

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Configuration

jwt.expiration=86400000
jwt.refresh-expiration=604800000
jwt.secret=404E635266556A586E3272357538782F413F428472B4B6250645367566B5970428472B4B6250645367566B5970
# Payment Configuration
stripe.api.key=${STRIPE_API_KEY:sk_test_placeholder}
payment.strategy=stripe
